
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Gamepad2, 
  Rocket, 
  Target, 
  Zap, 
  ChevronRight, 
  ChevronLeft, 
  Star, 
  Trophy,
  BrainCircuit,
  Layout,
  Layers,
  Code2,
  CheckCircle2,
  Award,
  ArrowRight,
  Info,
  Lightbulb,
  Upload,
  MessageSquare,
  Clock,
  FlaskConical,
  PlayCircle
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Card } from '@/components/ui/card';
import { toast } from 'sonner';
import '../../styles/ConstructionTheme.css';
import { professorApi } from '@/features/professor/services/professor.api';
import { SESSIONS_DATA, SessionStep, SessionConfig } from './LatamSessionData';

const X = ({ className, onClick }: { className?: string, onClick?: () => void }) => (
    <svg onClick={onClick} className={cn("cursor-pointer", className)} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
);

const Loader2 = ({ className }: { className?: string }) => (
    <svg className={cn("animate-spin", className)} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>
);

export const LatamSessionViewer = ({ sessionId, onClose }: { sessionId: string, onClose: () => void }) => {
    const [sessionKey, setSessionKey] = useState<string>("DB-GC-01");
    const [currentScreen, setCurrentScreen] = useState(1);
    const [isLiveActive, setIsLiveActive] = useState(false);
    const [liveTimer, setLiveTimer] = useState(300);
    const [reflection, setReflection] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [isCompleted, setIsCompleted] = useState(false);

    const [loading, setLoading] = useState(true);
    const [dynamicSession, setDynamicSession] = useState<SessionConfig | null>(null);

    useEffect(() => {
        const fetchDynamicData = async () => {
            if (!sessionId) return;
            // If sessionId is very high, it's likely a real DB ID (auto-generated by serial)
            // If it's a string like "DB-GC-01", we use static
            if (isNaN(Number(sessionId))) {
                setSessionKey(sessionId);
                setLoading(false);
                return;
            }

            try {
                setLoading(true);
                // We fetch levels of the module. For Latam dynamic, we usually have 1 level with the JSON
                const levels = await professorApi.getModuleLevels(sessionId);
                if (levels && levels.length > 0 && levels[0].descripcion) {
                    const payload = JSON.parse(levels[0].descripcion);
                    const { metadata, blocks } = payload;

                    // Transform blocks to steps
                    const steps: SessionStep[] = (blocks || []).map((block: any, idx: number) => {
                        const { data } = block;
                        const base = { id: idx + 1, title: metadata.title };

                        switch (block.type) {
                            case 'NARRATIVE':
                                return { ...base, type: 'story', title: data.titulo || metadata.title, narrative: data.texto, visualType: data.multimedia ? 'image' : undefined, visualUrl: data.multimedia };
                            case 'EVALUATION':
                                return { ...base, type: 'evaluation', question: data.pregunta, options: (data.opciones || []).map((o: string, i: number) => ({ label: o, correct: i === data.respuestaIndex })) };
                            case 'OPEN_QUESTION':
                                return { ...base, type: 'evaluation', question: data.pregunta, reflectionPrompt: 'Escribe tu respuesta aquí...' };
                            case 'STEP_BY_STEP':
                                return { ...base, type: 'exploration', title: data.titulo, steps: (data.pasos || []).map((p: string) => ({ title: 'Instrucción', desc: p })) };
                            case 'CHECKLIST':
                                return { ...base, type: 'exploration', title: data.titulo, steps: (data.items || []).map((it: string) => ({ title: 'Check', desc: it })) };
                            case 'REWARD':
                                return { ...base, type: 'achievement', title: '¡Misión Cumplida!', badgeName: data.insignia, rewardXp: data.xp };
                            case 'PROBLEM':
                                return { ...base, type: 'challenge', title: data.mision, narrative: data.restricciones };
                            default:
                                return { ...base, type: 'concept', title: 'Bloque Informativo', narrative: 'Contenido dinámico' };
                        }
                    });

                    setDynamicSession({
                        id: sessionId,
                        code: metadata.codigo || `LATAM-${sessionId}`,
                        title: metadata.title,
                        module: 'Personalizado',
                        level: metadata.tipoFlujo,
                        totalScreens: steps.length,
                        steps
                    });
                }
            } catch (err) {
                console.error("Error loading dynamic session:", err);
            } finally {
                setLoading(false);
            }
        };
        fetchDynamicData();
    }, [sessionId]);

    const session = dynamicSession || SESSIONS_DATA[sessionKey];
    
    // Add loading state check
    if (loading) {
        return (
            <div className="fixed inset-0 z-[110] bg-[#020617] flex items-center justify-center">
                 <Loader2 className="w-12 h-12 text-blue-500" />
            </div>
        );
    }

    if (!session) {
        return (
            <div className="fixed inset-0 z-[110] bg-[#020617] flex flex-col items-center justify-center text-white">
                <p>Sesión no encontrada o sin contenido dinámico.</p>
                <Button onClick={onClose} className="mt-4">Cerrar</Button>
            </div>
        );
    }
    const step = session.steps[currentScreen - 1];
    const totalScreens = session.totalScreens;

    const next = () => {
        if (step.type === 'evaluation' && !reflection) {
            toast.error("Por favor agrega tu evidencia antes de continuar.");
            return;
        }
        setCurrentScreen(curr => Math.min(curr + 1, totalScreens));
    };
    const prev = () => setCurrentScreen(curr => Math.max(curr - 1, 1));

    const handleSubmit = () => {
        setIsSubmitting(true);
        setTimeout(() => {
            setIsSubmitting(false);
            setIsCompleted(true);
            toast.success(`¡Misión completada! Has ganado la insignia: ${step.badgeName}`);
        }, 2000);
    };

    useEffect(() => {
        const checkLiveStatus = () => {
            const active = localStorage.getItem('latam_live_challenge_active') === 'true';
            if (active) setIsLiveActive(true);
        };
        checkLiveStatus();
        window.addEventListener('storage', checkLiveStatus);
        const interval = setInterval(checkLiveStatus, 2000);
        return () => {
            window.removeEventListener('storage', checkLiveStatus);
            clearInterval(interval);
        };
    }, []);

    useEffect(() => {
        let interval: any;
        if (isLiveActive && liveTimer > 0) {
            interval = setInterval(() => setLiveTimer(t => t - 1), 1000);
        }
        return () => clearInterval(interval);
    }, [isLiveActive, liveTimer]);

    const formatTime = (seconds: number) => {
        const mins = Math.floor(seconds / 60);
        const secs = seconds % 60;
        return `${mins}:${secs.toString().padStart(2, '0')}`;
    };

    const DynamicIcon = ({ type }: { type: string }) => {
        switch(type) {
            case 'story': return <Rocket className="w-8 h-8 text-blue-400" />;
            case 'challenge': return <Target className="w-8 h-8 text-indigo-400" />;
            case 'live': return <Zap className="w-8 h-8 text-amber-400" />;
            case 'achievement': return <Award className="w-8 h-8 text-emerald-400" />;
            default: return <BrainCircuit className="w-8 h-8 text-blue-400" />;
        }
    };

    return (
        <div className="fixed inset-0 z-[110] bg-[#020617] flex flex-col font-sans overflow-hidden">
            {/* AMBIENT BACKGROUND */}
            <div className="absolute inset-0 z-0">
                <img 
                    src="/assets/latam/bg_studio.png" 
                    className="w-full h-full object-cover opacity-40 mix-blend-screen"
                    alt="Studio Background"
                />
                <div className="absolute inset-0 bg-gradient-to-b from-[#020617]/80 via-transparent to-[#020617]" />
                <div className="absolute inset-0 construction-grid opacity-30" />
                <div className="hud-scanner" />
            </div>

            {/* PROGRESS HEADER */}
            <div className="header-glass backdrop-blur-xl border-b border-blue-500/10 px-8 pt-8 pb-4 flex items-center justify-between relative z-20 shrink-0">
                <div className="flex items-center gap-6">
                    <div className="w-12 h-12 bg-blue-500/10 border border-blue-500/20 rounded-2xl flex items-center justify-center neon-border">
                        <Rocket className="text-blue-400 w-6 h-6" />
                    </div>
                    <div>
                        <h1 className="text-xl font-black italic uppercase tracking-tighter text-white leading-none">
                            Academy <span className="text-blue-500 underline decoration-blue-500/30">LATAM</span>
                        </h1>
                        <p className="text-[10px] font-black text-blue-500/60 uppercase tracking-widest mt-1">{session.level} · {session.code}</p>
                    </div>
                </div>

                <div className="flex-1 max-w-lg mx-12 hidden md:block">
                    <div className="flex justify-between mb-2 items-end">
                        <span className="text-[9px] font-black uppercase text-slate-400 tracking-[0.2em]">{session.title}</span>
                        <span className="text-[9px] font-black uppercase text-blue-400 tracking-widest flex items-center gap-2">
                             PROTOCOLO DE CARGA <span className="text-white tabular-nums">{Math.round((currentScreen / totalScreens) * 100)}%</span>
                        </span>
                    </div>
                    <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden border border-white/5">
                        <motion.div 
                            initial={{ width: 0 }}
                            animate={{ width: `${(currentScreen / totalScreens) * 100}%` }}
                            className="h-full bg-gradient-to-r from-blue-600 to-cyan-400 shadow-[0_0_10px_rgba(59,130,246,0.5)]"
                        />
                    </div>
                </div>

                <X onClick={onClose} className="text-white w-6 h-6 hover:text-blue-400 transition-colors" />
            </div>

            {/* MAIN INTERACTIVE AREA */}
            <div className="flex-1 flex relative z-10 px-8 py-6 gap-8 overflow-hidden">
                
                {/* LEFT COLUMN: MENTOR CHARACTER */}
                <div className="hidden lg:flex flex-col items-center justify-end w-[35%] pb-12 relative">
                    <AnimatePresence mode="wait">
                        <motion.div 
                            key={`mentor-${currentScreen}`}
                            initial={{ opacity: 0, x: -50, scale: 0.9 }}
                            animate={{ opacity: 1, x: 0, scale: 1 }}
                            exit={{ opacity: 0, x: -50, scale: 0.9 }}
                            transition={{ type: 'spring', damping: 20 }}
                            className="relative z-10"
                        >
                            <img 
                                src="/assets/latam/mentor_owl.png" 
                                className="w-[400px] h-auto mentor-aura"
                                alt="Mentor Owl"
                            />
                            
                            {/* Dialogue Bubble */}
                            {step.narrative && (
                                <motion.div 
                                    initial={{ opacity: 0, y: 20, scale: 0.8 }}
                                    animate={{ opacity: 1, y: 0, scale: 1 }}
                                    transition={{ delay: 0.3 }}
                                    className="absolute -top-32 -right-12 w-[450px] bubble-glass text-slate-800"
                                >
                                    <MessageSquare className="absolute -top-3 -left-3 w-8 h-8 text-blue-500 fill-blue-50 bg-white rounded-full p-1.5 border border-blue-100" />
                                    <p className="text-sm font-bold leading-relaxed">{step.narrative}</p>
                                    <div className="mt-3 flex items-center gap-2">
                                        <div className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse" />
                                        <span className="text-[10px] uppercase font-black tracking-widest text-blue-600">{step.mentorTitle || "Instrucciones del Mentor"}</span>
                                    </div>
                                </motion.div>
                            )}
                        </motion.div>
                    </AnimatePresence>
                    
                    {/* HUD Decorative Grids */}
                    <div className="absolute bottom-0 left-0 w-full h-full pointer-events-none z-0 overflow-hidden">
                        <div className="absolute bottom-10 left-10 w-64 h-64 border border-blue-500/10 rounded-full hud-spinner" />
                        <div className="absolute bottom-20 left-20 w-48 h-48 border border-blue-500/5 rounded-full hud-spinner" style={{ animationDirection: 'reverse' }} />
                    </div>
                </div>

                {/* RIGHT COLUMN: SIMULATION CONTENT */}
                <div className="flex-1 flex flex-col justify-center max-w-4xl mx-auto lg:mx-0">
                    <Card className="w-full quantum-card overflow-hidden flex flex-col p-8 md:p-12 relative min-h-[500px]">
                        <AnimatePresence mode="wait">
                            {isCompleted ? (
                                <motion.div 
                                    initial={{ scale: 0.9, opacity: 0 }} 
                                    animate={{ scale: 1, opacity: 1 }} 
                                    className="text-center space-y-10 py-12"
                                >
                                    <div className="relative inline-block">
                                        <div className="absolute inset-0 bg-blue-500/20 blur-[60px] rounded-full animate-pulse" />
                                        <div className="w-48 h-48 bg-gradient-to-br from-blue-600 to-indigo-700 rounded-[3rem] flex items-center justify-center mx-auto shadow-[0_20px_50px_rgba(59,130,246,0.3)] neon-border relative group">
                                            <DynamicIcon type="achievement" />
                                            <div className="absolute inset-0 rounded-[3rem] border border-white/20" />
                                        </div>
                                    </div>
                                    
                                    <div className="space-y-4">
                                        <h3 className="text-5xl font-black italic text-white uppercase tracking-tighter">¡MISIÓN COMPLETADA!</h3>
                                        <div className="bg-blue-500/10 text-blue-400 border border-blue-500/20 px-8 py-3 rounded-2xl font-black uppercase text-sm inline-block tracking-widest">
                                            INSIGNIA ADQUIRIDA: {step.badgeName || "Creador de Software"}
                                        </div>
                                    </div>
                                    
                                    <p className="text-slate-400 font-medium max-w-md mx-auto text-lg leading-relaxed">
                                        Tu rendimiento ha sido excepcional. Se han transferido {session.steps[totalScreens-1].rewardXp} XP a tu banco de datos.
                                    </p>
                                    
                                    <Button 
                                        onClick={onClose} 
                                        className="bg-white text-slate-900 hover:bg-blue-50 rounded-2xl h-16 px-12 font-black uppercase tracking-[0.2em] text-sm shadow-[0_10px_30px_rgba(255,255,255,0.1)] active:scale-95 transition-all"
                                    >
                                        Finalizar Secuencia
                                    </Button>
                                </motion.div>
                            ) : (
                                <motion.div 
                                    key={currentScreen}
                                    initial={{ opacity: 0, x: 30 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    exit={{ opacity: 0, x: -30 }}
                                    className="w-full flex-1 flex flex-col"
                                >
                                    {/* Content Header */}
                                    <div className="flex items-start justify-between mb-10">
                                        <div className="space-y-3">
                                            <div className="flex items-center gap-4">
                                                <div className="w-14 h-14 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center neon-border">
                                                    <DynamicIcon type={step.type} />
                                                </div>
                                                <div>
                                                    <h2 className="text-4xl font-black italic uppercase tracking-tighter text-white">{step.title}</h2>
                                                    {step.subtitle && <p className="text-blue-500/60 font-black uppercase tracking-[0.3em] text-[10px]">{step.subtitle}</p>}
                                                </div>
                                            </div>
                                        </div>
                                        {step.type === 'achievement' && <Star className="w-12 h-12 text-amber-400 fill-current animate-pulse drop-shadow-[0_0_15px_rgba(251,191,36,0.5)]" />}
                                    </div>

                                    {/* Dynamic Media/Interaction Panel */}
                                    <div className="flex-1 quantum-scroll overflow-y-auto pr-4 space-y-8">
                                        
                                        {/* Fallback for Mobile (Show narrative if mentor is hidden) */}
                                        <div className="lg:hidden">
                                            {step.narrative && (
                                                <div className="bg-white/5 border border-white/10 p-6 rounded-2xl mb-6">
                                                    <p className="text-slate-300 font-medium italic text-lg leading-relaxed">"{step.narrative}"</p>
                                                </div>
                                            )}
                                        </div>

                                        {step.type === 'story' && step.visualType === 'video' && (
                                            <div className="aspect-video bg-black/40 rounded-[2.5rem] overflow-hidden flex items-center justify-center border border-white/5 relative group">
                                                <div className="absolute inset-0 bg-blue-500/5 group-hover:bg-transparent transition-colors" />
                                                <div className="text-center text-white space-y-6 relative z-10">
                                                    <div className="w-24 h-24 bg-white/10 rounded-full flex items-center justify-center mx-auto backdrop-blur-md border border-white/10 group-hover:scale-110 transition-transform">
                                                        <PlayCircle className="w-12 h-12 text-blue-400" />
                                                    </div>
                                                    <p className="font-black uppercase tracking-[0.4em] text-xs text-blue-400/80">Stream de Datos: {step.subtitle}</p>
                                                </div>
                                            </div>
                                        )}

                                        {(step.type === 'question' || step.type === 'evaluation') && (
                                            <div className="space-y-8">
                                                <div className="bg-slate-900/40 p-1 rounded-3xl border border-white/5">
                                                    <div className="p-8 rounded-[1.4rem] border border-white/5 bg-gradient-to-br from-white/5 to-transparent">
                                                        <h4 className="text-2xl font-bold text-white tracking-tight">{step.question}</h4>
                                                    </div>
                                                </div>

                                                <div className="grid grid-cols-1 gap-4">
                                                    {step.options?.map((opt, i) => (
                                                        <Button 
                                                            key={i} 
                                                            variant="outline" 
                                                            onClick={() => opt.correct ? toast.success("ACCESO CONCEDIDO") : toast.error("CONEXIÓN FALLIDA")}
                                                            className="h-20 rounded-[1.5rem] border border-white/10 bg-white/5 hover:bg-blue-600 hover:border-blue-400 text-white font-black justify-start px-8 gap-6 transition-all group"
                                                        >
                                                            <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center text-xs font-black group-hover:bg-white group-hover:text-blue-600 transition-colors">
                                                                {String.fromCharCode(65 + i)}
                                                            </div>
                                                            <span className="text-lg tracking-tight uppercase italic">{opt.label}</span>
                                                        </Button>
                                                    ))}
                                                </div>

                                                {step.type === 'evaluation' && (
                                                    <div className="mt-8 space-y-4">
                                                        <label className="text-[10px] font-black uppercase text-blue-500/60 flex items-center gap-3 tracking-[0.3em]">
                                                            <div className="w-1.5 h-1.5 rounded-full bg-blue-500" /> CAPTURA DE EVIDENCIA REQUERIDA
                                                        </label>
                                                        <textarea 
                                                            value={reflection}
                                                            onChange={(e) => setReflection(e.target.value)}
                                                            placeholder={step.reflectionPrompt || "Ingresar logs de reflexión..."}
                                                            className="w-full h-32 p-6 rounded-[2rem] bg-white/5 border border-white/10 focus:border-blue-500/50 outline-none text-white font-medium placeholder:text-slate-600 quantum-scroll"
                                                        />
                                                    </div>
                                                )}
                                            </div>
                                        )}

                                        {step.type === 'live' && (
                                            <div className="flex flex-col items-center justify-center text-center space-y-10 bg-blue-900/10 p-16 rounded-[3rem] border border-blue-500/10 relative overflow-hidden group">
                                                <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(59,130,246,0.1),transparent)]" />
                                                {!isLiveActive ? (
                                                    <>
                                                        <div className="relative">
                                                            <div className="absolute inset-0 bg-blue-500/20 blur-3xl rounded-full animate-pulse" />
                                                            <div className="w-32 h-32 bg-white/5 rounded-full flex items-center justify-center shadow-inner border border-white/10 relative z-10">
                                                                <Clock className="w-14 h-14 text-blue-400 animate-pulse" />
                                                            </div>
                                                        </div>
                                                        <div className="space-y-4 relative z-10">
                                                            <h4 className="text-4xl font-black text-white uppercase italic tracking-tighter">Sincronizando con Docente</h4>
                                                            <p className="text-blue-400 font-bold uppercase tracking-widest text-xs">El protocolo de reto aún no ha sido activado.</p>
                                                        </div>
                                                        <Button 
                                                            onClick={() => setIsLiveActive(true)} 
                                                            variant="ghost" 
                                                            className="text-slate-600 text-[10px] font-bold uppercase tracking-[0.4em] hover:text-blue-400 relative z-10"
                                                        >
                                                            SIMULAR OVERRIDE (DEBUG)
                                                        </Button>
                                                    </>
                                                ) : (
                                                    <>
                                                        <div className="text-[120px] font-black text-blue-500 tracking-tighter tabular-nums leading-none drop-shadow-[0_0_30px_rgba(59,130,246,0.3)]">
                                                            {formatTime(liveTimer)}
                                                        </div>
                                                        <div className="space-y-4 relative z-10">
                                                            <h4 className="text-5xl font-black text-white uppercase italic tracking-tighter">¡SECUENCIA ACTIVADA!</h4>
                                                            <p className="text-cyan-400 font-black uppercase tracking-[0.4em] text-[10px]">TIEMPO LÍMITE PARA FINALIZACIÓN DE TAREA EN GDEVELOP</p>
                                                        </div>
                                                    </>
                                                )}
                                            </div>
                                        )}

                                        {step.steps && (
                                            <div className="grid md:grid-cols-2 gap-4">
                                                {step.steps.map((s, i) => (
                                                    <Card key={i} className="p-8 rounded-[2rem] bg-white/5 border border-white/5 group hover:border-blue-500/30 hover:bg-white/10 transition-all">
                                                        <div className="flex gap-6">
                                                            <div className="w-12 h-12 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center font-black text-blue-500 shrink-0 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                                                                {(i + 1).toString().padStart(2, '0')}
                                                            </div>
                                                            <div>
                                                                <h5 className="font-black text-white uppercase italic text-sm tracking-tight mb-2">{s.title}</h5>
                                                                <p className="text-[13px] text-slate-400 font-medium leading-relaxed leading-snug">{s.desc}</p>
                                                            </div>
                                                        </div>
                                                    </Card>
                                                ))}
                                            </div>
                                        )}
                                    </div>

                                    {/* Footer Content Nav */}
                                    <div className="flex items-center justify-between pt-10 border-t border-white/5 mt-8 shrink-0">
                                        <Button 
                                            variant="ghost" 
                                            onClick={prev} 
                                            className={cn("text-slate-500 font-black tracking-widest text-[10px] hover:text-white transition-all uppercase", currentScreen === 1 && "opacity-0 pointer-events-none")}
                                        >
                                            <ChevronLeft className="mr-2 w-4 h-4" /> REBOBINAR
                                        </Button>
                                        
                                        <div className="flex gap-3">
                                            {session.steps.map((_, i) => (
                                                <div 
                                                    key={i} 
                                                    className={cn(
                                                        "h-1.5 rounded-full transition-all duration-500", 
                                                        i + 1 === currentScreen 
                                                            ? "bg-blue-500 w-8 shadow-[0_0_10px_rgba(59,130,246,0.5)]" 
                                                            : i + 1 < currentScreen 
                                                                ? "bg-blue-900 w-1.5" 
                                                                : "bg-white/10 w-1.5"
                                                    )} 
                                                />
                                            ))}
                                        </div>

                                        {currentScreen < totalScreens ? (
                                            <Button 
                                                onClick={next} 
                                                className="bg-blue-600 hover:bg-blue-500 text-white rounded-[1.5rem] h-16 px-10 font-black uppercase tracking-[0.2em] text-xs gap-3 shadow-[0_10px_30px_rgba(37,99,235,0.2)] active:scale-95 transition-all"
                                            >
                                                SIGUIENTE FASE
                                                <ChevronRight className="w-4 h-4" />
                                            </Button>
                                        ) : (
                                            <div className="w-40" />
                                        )}
                                    </div>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </Card>
                </div>
            </div>
        </div>
    );
};
